# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'SpringApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpringApp
  pod 'Spring', :git => 'https://github.com/LexDeBash/Spring.git'
end
