//
//  GreetingModels.swift
//  CleanSwiftModule
//
//  Created by Виталий Шаповалов on 08.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias GreetingRequest = Greeting.ShowGreeting.Request
typealias GreetingResponse = Greeting.ShowGreeting.Response
typealias GreetingViewModel = Greeting.ShowGreeting.ViewModel


enum Greeting {
    
    // MARK: Use cases
    enum ShowGreeting {
        
        // broker between viewcontroller and interactor
        struct Request {
        }
        
        // broker between interactor and presenter
        struct Response {
            let name: String
            let surname: String
        }
        
        // broker between presenter and viewcontroller
        struct ViewModel {
            let greeting: String
        }
    }
}
