//
//  GreetingViewController.swift
//  CleanSwiftModule
//
//  Created by Виталий Шаповалов on 08.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GreetingDisplayLogic: AnyObject {
    func displayGreeting(viewModel: GreetingViewModel)
}

class GreetingViewController: UIViewController, GreetingDisplayLogic {
    
    @IBOutlet private var greetingLabel: UILabel!
    
    var interactor: GreetingBusinessLogic?
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        GreetingConfigurator.shared.configure(with: self)
    }

    // MARK: Do something

    func displayGreeting(viewModel: GreetingViewModel) {
        greetingLabel.text = viewModel.greeting
    }
    
    @IBAction func showGreetingPressed() {
        let request = GreetingRequest()
        interactor?.showGreeting(request: request)
    }
}
